package com.trishakti.crm.domain.enums;

public enum ActivityType {
    CREATED, ASSIGNED, REASSIGNED, STATUS_CHANGE, CALL, NOTE, FOLLOW_UP_SET, FOLLOW_UP_DONE,
    SITE_VISIT_SCHEDULED, SITE_VISIT_DONE, BOOKING, PAYMENT, IMPORT, EMAIL, WHATSAPP, SYSTEM
}
