package com.trishakti.crm.domain.enums;

public enum NotificationType {
    LEAD_ASSIGNED, FOLLOW_UP_DUE, FOLLOW_UP_OVERDUE, SITE_VISIT_SCHEDULED, SITE_VISIT_REMINDER,
    BOOKING_CREATED, PAYMENT_DUE, PAYMENT_RECEIVED, TASK_ASSIGNED, TASK_DUE, LEAD_STATUS_CHANGE, SYSTEM
}
