package com.trishakti.crm.domain.enums;

public enum SourceChannel {
    FACEBOOK, GOOGLE, INSTAGRAM, YOUTUBE, NEWSPAPER, HOARDING, WALK_IN, REFERRAL,
    PORTAL_99ACRES, PORTAL_MAGICBRICKS, PORTAL_HOUSING, WEBSITE, WHATSAPP, EXPO, OTHER
}
