-- =====================================================================
--  Shri Trishakti Infra Realtors Pvt Ltd — Property CRM
--  Reference DDL (PostgreSQL 14+).
--  The running app generates this via Hibernate (ddl-auto=update);
--  this file is the authoritative documented schema.
--
--  Notes
--   * `users` and `leads` are pluralised because USER is reserved in PostgreSQL
--     and LEAD is a reserved window function name in several engines.
--   * Enum-backed columns are plain VARCHAR here; Hibernate additionally emits a
--     CHECK (col IN (...)) constraint for each one.
--   * The exact DDL Hibernate produces is written to
--     backend/target/generated-schema/postgres-schema.sql by
--     PostgresSchemaGenerationTest — diff against this file when mappings change.
-- =====================================================================

-- ---------- Identity & Org ----------
CREATE TABLE role (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(40) NOT NULL UNIQUE,
  description  VARCHAR(200),
  created_at   TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by   VARCHAR(100), updated_by VARCHAR(100), version BIGINT
);

CREATE TABLE team (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(120) NOT NULL,
  description  VARCHAR(300),
  manager_id   BIGINT,
  active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by   VARCHAR(100), updated_by VARCHAR(100), version BIGINT
);

CREATE TABLE users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name     VARCHAR(150) NOT NULL,
  username      VARCHAR(80)  NOT NULL,
  email         VARCHAR(150) NOT NULL,
  password_hash VARCHAR(100) NOT NULL,
  phone         VARCHAR(20),
  team_id       BIGINT,
  manager_id    BIGINT,
  active        BOOLEAN NOT NULL DEFAULT TRUE,
  last_login_at TIMESTAMPTZ(6),
  created_at    TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by    VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT uk_users_username UNIQUE (username),
  CONSTRAINT uk_users_email    UNIQUE (email),
  CONSTRAINT fk_users_team     FOREIGN KEY (team_id)    REFERENCES team(id),
  CONSTRAINT fk_users_manager  FOREIGN KEY (manager_id) REFERENCES users(id)
);

ALTER TABLE team ADD CONSTRAINT fk_team_manager FOREIGN KEY (manager_id) REFERENCES users(id);

CREATE TABLE user_role (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES role(id)
);

CREATE TABLE refresh_token (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL,
  token_hash  VARCHAR(128) NOT NULL,
  expires_at  TIMESTAMPTZ(6) NOT NULL,
  revoked     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by  VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT fk_rt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_refresh_token_hash ON refresh_token (token_hash);
CREATE INDEX idx_refresh_user       ON refresh_token (user_id);

-- ---------- Property ----------
CREATE TABLE property_project (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(150) NOT NULL,
  location    VARCHAR(150),
  city        VARCHAR(80),
  description VARCHAR(500),
  active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by  VARCHAR(100), updated_by VARCHAR(100), version BIGINT
);

CREATE TABLE property (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id    BIGINT,
  title         VARCHAR(160) NOT NULL,
  property_type VARCHAR(30)  NOT NULL,
  unit_number   VARCHAR(40),
  location      VARCHAR(150),
  city          VARCHAR(80),
  area_sqft     NUMERIC(12,2),
  price         NUMERIC(14,2),
  bedrooms      INTEGER,
  bathrooms     INTEGER,
  facing        VARCHAR(30),
  status        VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
  description   VARCHAR(1000),
  created_at    TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by    VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT fk_property_project FOREIGN KEY (project_id) REFERENCES property_project(id)
);
CREATE INDEX idx_property_type_status ON property (property_type, status);
CREATE INDEX idx_property_city_loc    ON property (city, location);

-- ---------- Customer ----------
CREATE TABLE customer (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name       VARCHAR(150) NOT NULL,
  mobile          VARCHAR(20)  NOT NULL,
  alt_mobile      VARCHAR(20),
  email           VARCHAR(150),
  address         VARCHAR(300),
  city            VARCHAR(80),
  id_proof_type   VARCHAR(40),
  id_proof_number VARCHAR(60),
  notes           VARCHAR(1000),
  source_lead_id  BIGINT,
  created_at      TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by      VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT uk_customer_mobile UNIQUE (mobile)
);
CREATE INDEX idx_customer_mobile ON customer (mobile);

-- ---------- Lead ----------
CREATE TABLE leads (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name          VARCHAR(150) NOT NULL,
  mobile                 VARCHAR(20)  NOT NULL,
  email                  VARCHAR(150),
  source                 VARCHAR(120),
  source_channel         VARCHAR(30),
  property_type          VARCHAR(30),
  budget_min             NUMERIC(14,2),
  budget_max             NUMERIC(14,2),
  preferred_location     VARCHAR(150),
  status                 VARCHAR(30) NOT NULL DEFAULT 'NEW',
  priority               VARCHAR(10) DEFAULT 'WARM',
  assigned_user_id       BIGINT,
  created_by_user_id     BIGINT,
  interested_property_id BIGINT,
  converted_customer_id  BIGINT,
  next_follow_up_at      TIMESTAMPTZ(6),
  last_contacted_at      TIMESTAMPTZ(6),
  notes                  VARCHAR(4000),
  lost_reason            VARCHAR(255),
  deleted                BOOLEAN NOT NULL DEFAULT FALSE,
  created_at             TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by             VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT fk_lead_assignee FOREIGN KEY (assigned_user_id)       REFERENCES users(id),
  CONSTRAINT fk_lead_creator  FOREIGN KEY (created_by_user_id)     REFERENCES users(id),
  CONSTRAINT fk_lead_property FOREIGN KEY (interested_property_id) REFERENCES property(id),
  CONSTRAINT fk_lead_customer FOREIGN KEY (converted_customer_id)  REFERENCES customer(id)
);
CREATE INDEX idx_lead_status          ON leads (status);
CREATE INDEX idx_lead_assignee_status ON leads (assigned_user_id, status);
CREATE INDEX idx_lead_follow_up       ON leads (next_follow_up_at);
CREATE INDEX idx_lead_mobile          ON leads (mobile);
CREATE INDEX idx_lead_source_channel  ON leads (source_channel);
CREATE INDEX idx_lead_created_at      ON leads (created_at);

CREATE TABLE lead_assignment (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id        BIGINT NOT NULL,
  from_user_id   BIGINT,
  to_user_id     BIGINT,
  assigned_by_id BIGINT,
  reason         VARCHAR(255),
  assigned_at    TIMESTAMPTZ(6) NOT NULL,
  created_at     TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by     VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT fk_la_lead FOREIGN KEY (lead_id)        REFERENCES leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_la_from FOREIGN KEY (from_user_id)   REFERENCES users(id),
  CONSTRAINT fk_la_to   FOREIGN KEY (to_user_id)     REFERENCES users(id),
  CONSTRAINT fk_la_by   FOREIGN KEY (assigned_by_id) REFERENCES users(id)
);
CREATE INDEX idx_assignment_lead ON lead_assignment (lead_id);

CREATE TABLE lead_activity (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id       BIGINT NOT NULL,
  type          VARCHAR(30) NOT NULL,
  from_status   VARCHAR(30),
  to_status     VARCHAR(30),
  summary       VARCHAR(255) NOT NULL,
  detail        VARCHAR(4000),
  actor_user_id BIGINT,
  occurred_at   TIMESTAMPTZ(6) NOT NULL,
  created_at    TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by    VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT fk_activity_lead  FOREIGN KEY (lead_id)       REFERENCES leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_activity_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
);
CREATE INDEX idx_activity_lead_time ON lead_activity (lead_id, occurred_at);

-- ---------- Calling & Follow-up ----------
CREATE TABLE call_log (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id           BIGINT NOT NULL,
  caller_id         BIGINT,
  direction         VARCHAR(12) NOT NULL DEFAULT 'OUTBOUND',
  outcome           VARCHAR(20) NOT NULL,
  disposition       VARCHAR(25),
  duration_seconds  INTEGER,
  notes             VARCHAR(2000),
  called_at         TIMESTAMPTZ(6) NOT NULL,
  next_follow_up_at TIMESTAMPTZ(6),
  created_at        TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by        VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT fk_call_lead   FOREIGN KEY (lead_id)   REFERENCES leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_call_caller FOREIGN KEY (caller_id) REFERENCES users(id)
);
CREATE INDEX idx_call_lead_time   ON call_log (lead_id, called_at);
CREATE INDEX idx_call_caller_time ON call_log (caller_id, called_at);

CREATE TABLE follow_up (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id      BIGINT NOT NULL,
  owner_id     BIGINT,
  due_at       TIMESTAMPTZ(6) NOT NULL,
  channel      VARCHAR(15) NOT NULL DEFAULT 'CALL',
  status       VARCHAR(15) NOT NULL DEFAULT 'PENDING',
  notes        VARCHAR(1000),
  completed_at TIMESTAMPTZ(6),
  notified     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by   VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT fk_fu_lead  FOREIGN KEY (lead_id)  REFERENCES leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_fu_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);
CREATE INDEX idx_followup_due          ON follow_up (due_at);
CREATE INDEX idx_followup_owner_status ON follow_up (owner_id, status);

-- ---------- Site Visit ----------
CREATE TABLE site_visit (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id             BIGINT NOT NULL,
  property_id         BIGINT,
  sales_executive_id  BIGINT,
  scheduled_at        TIMESTAMPTZ(6) NOT NULL,
  status              VARCHAR(15) NOT NULL DEFAULT 'SCHEDULED',
  result              VARCHAR(20),
  feedback            VARCHAR(2000),
  pickup_required     BOOLEAN NOT NULL DEFAULT FALSE,
  completed_at        TIMESTAMPTZ(6),
  rating              INTEGER,
  created_at          TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by          VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT fk_sv_lead     FOREIGN KEY (lead_id)            REFERENCES leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_sv_property FOREIGN KEY (property_id)        REFERENCES property(id),
  CONSTRAINT fk_sv_exec     FOREIGN KEY (sales_executive_id) REFERENCES users(id)
);
CREATE INDEX idx_sitevisit_scheduled   ON site_visit (scheduled_at);
CREATE INDEX idx_sitevisit_exec_status ON site_visit (sales_executive_id, status);

-- ---------- Sales / Purchase / Payment ----------
CREATE TABLE booking (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id               BIGINT NOT NULL,
  site_visit_id         BIGINT,
  property_id           BIGINT NOT NULL,
  customer_id           BIGINT,
  sales_executive_id    BIGINT,
  booking_number        VARCHAR(40) NOT NULL,
  status                VARCHAR(15) NOT NULL DEFAULT 'NEGOTIATION',
  quoted_price          NUMERIC(14,2),
  negotiated_price      NUMERIC(14,2),
  discount              NUMERIC(14,2),
  token_amount          NUMERIC(14,2),
  booking_date          DATE,
  expected_closure_date DATE,
  notes                 VARCHAR(2000),
  cancel_reason         VARCHAR(255),
  created_at            TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by            VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT uk_booking_number UNIQUE (booking_number),
  CONSTRAINT fk_bk_lead     FOREIGN KEY (lead_id)            REFERENCES leads(id),
  CONSTRAINT fk_bk_sv       FOREIGN KEY (site_visit_id)      REFERENCES site_visit(id),
  CONSTRAINT fk_bk_property FOREIGN KEY (property_id)        REFERENCES property(id),
  CONSTRAINT fk_bk_customer FOREIGN KEY (customer_id)        REFERENCES customer(id),
  CONSTRAINT fk_bk_exec     FOREIGN KEY (sales_executive_id) REFERENCES users(id)
);
CREATE INDEX idx_booking_status ON booking (status);
CREATE INDEX idx_booking_exec   ON booking (sales_executive_id);

CREATE TABLE purchase (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id        BIGINT NOT NULL,
  property_id       BIGINT NOT NULL,
  customer_id       BIGINT,
  sale_deed_number  VARCHAR(60),
  final_price       NUMERIC(14,2),
  total_paid        NUMERIC(14,2) DEFAULT 0,
  balance           NUMERIC(14,2),
  status            VARCHAR(15) NOT NULL DEFAULT 'IN_PROGRESS',
  agreement_date    DATE,
  registration_date DATE,
  possession_date   DATE,
  created_at        TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by        VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT uk_purchase_booking UNIQUE (booking_id),
  CONSTRAINT fk_pu_booking  FOREIGN KEY (booking_id)  REFERENCES booking(id),
  CONSTRAINT fk_pu_property FOREIGN KEY (property_id) REFERENCES property(id),
  CONSTRAINT fk_pu_customer FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE payment (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id       BIGINT,
  purchase_id      BIGINT,
  type             VARCHAR(20) NOT NULL,
  mode             VARCHAR(20),
  amount           NUMERIC(14,2) NOT NULL,
  due_date         DATE,
  paid_date        DATE,
  status           VARCHAR(12) NOT NULL DEFAULT 'DUE',
  reference_number VARCHAR(80),
  remarks          VARCHAR(500),
  created_at       TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by       VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT fk_pay_booking  FOREIGN KEY (booking_id)  REFERENCES booking(id)  ON DELETE CASCADE,
  CONSTRAINT fk_pay_purchase FOREIGN KEY (purchase_id) REFERENCES purchase(id) ON DELETE CASCADE
);
CREATE INDEX idx_payment_booking    ON payment (booking_id);
CREATE INDEX idx_payment_purchase   ON payment (purchase_id);
CREATE INDEX idx_payment_status_due ON payment (status, due_date);

-- ---------- Task / Notification / Audit ----------
CREATE TABLE task (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        VARCHAR(200) NOT NULL,
  description  VARCHAR(2000),
  type         VARCHAR(25) NOT NULL DEFAULT 'GENERAL',
  assignee_id  BIGINT,
  lead_id      BIGINT,
  due_at       TIMESTAMPTZ(6),
  priority     VARCHAR(10) NOT NULL DEFAULT 'MEDIUM',
  status       VARCHAR(15) NOT NULL DEFAULT 'OPEN',
  reminder_at  TIMESTAMPTZ(6),
  notified     BOOLEAN NOT NULL DEFAULT FALSE,
  completed_at TIMESTAMPTZ(6),
  created_at   TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by   VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT fk_task_assignee FOREIGN KEY (assignee_id) REFERENCES users(id),
  CONSTRAINT fk_task_lead     FOREIGN KEY (lead_id)     REFERENCES leads(id) ON DELETE CASCADE
);
CREATE INDEX idx_task_assignee_status ON task (assignee_id, status);
CREATE INDEX idx_task_due             ON task (due_at);
CREATE INDEX idx_task_reminder        ON task (reminder_at, notified);

CREATE TABLE notification (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id BIGINT NOT NULL,
  type         VARCHAR(30) NOT NULL,
  title        VARCHAR(160) NOT NULL,
  body         VARCHAR(1000),
  entity_type  VARCHAR(40),
  entity_id    BIGINT,
  is_read      BOOLEAN NOT NULL DEFAULT FALSE,
  read_at      TIMESTAMPTZ(6),
  created_at   TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by   VARCHAR(100), updated_by VARCHAR(100), version BIGINT,
  CONSTRAINT fk_notif_recipient FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_notif_recipient_read ON notification (recipient_id, is_read);
CREATE INDEX idx_notif_created        ON notification (created_at);

CREATE TABLE audit_log (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_username VARCHAR(100),
  action         VARCHAR(80) NOT NULL,
  entity_type    VARCHAR(60),
  entity_id      BIGINT,
  before_json    TEXT,
  after_json     TEXT,
  ip_address     VARCHAR(60),
  user_agent     VARCHAR(255),
  at             TIMESTAMPTZ(6) NOT NULL,
  created_at     TIMESTAMPTZ(6), updated_at TIMESTAMPTZ(6),
  created_by     VARCHAR(100), updated_by VARCHAR(100), version BIGINT
);
CREATE INDEX idx_audit_entity ON audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_at     ON audit_log (at);
CREATE INDEX idx_audit_actor  ON audit_log (actor_username);
